version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - testifylint
    - unused
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
        path: .*_test.go
      - linters:
          - bodyclose
        path: router/timeout_response.go
      # False positives on CGO generated code
      - linters:
          - staticcheck
        path: vips/.*
        text: 'SA4000:'
      # False positives on CGO generated code
      - linters:
          - gocritic
        path: vips/.*
        text: dupSubExpr
      # False positives on CGO generated code
      - linters:
          - staticcheck
        text: 'ST1005:'
    paths:
      - .tmp
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .tmp
      - vendor
      - third_party$
      - builtin$
      - examples$
